from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))


def test_postgres_engine_url_uses_environment(monkeypatch):
    monkeypatch.setenv("POSTGRES_HOST", "postgres")
    monkeypatch.setenv("POSTGRES_PORT", "5432")
    monkeypatch.setenv("POSTGRES_USER", "ugm_app")
    monkeypatch.setenv("POSTGRES_PASSWORD", "not-a-real-secret")
    monkeypatch.setenv("POSTGRES_DB", "ugm_analytics")

    from app.db import build_database_url

    url = build_database_url()
    assert url.drivername == "postgresql+psycopg"
    assert url.host == "postgres"
    assert url.port == 5432
    assert url.database == "ugm_analytics"
    assert url.username == "ugm_app"


def test_deploy_compose_requires_every_variable():
    """compose.yml harus GAGAL kalau .env tidak lengkap, bukan diam-diam pakai string kosong."""
    import re

    compose_path = ROOT / "deploy" / "compose.yml"
    env_example_path = ROOT / "deploy" / ".env.example"
    assert compose_path.is_file(), "deploy/compose.yml must exist"
    assert env_example_path.is_file(), "deploy/.env.example must exist"

    # Komentar sering memuat contoh sintaks, jadi abaikan dulu; yang diperiksa hanya baris aktif.
    compose_text = "\n".join(
        line for line in compose_path.read_text(encoding="utf-8").splitlines() if not line.lstrip().startswith("#")
    )
    example_text = env_example_path.read_text(encoding="utf-8")

    # $$VAR (healthcheck) sengaja dilewati: itu escape Compose, bukan interpolasi host.
    raw = re.findall(r"(?<!\$)\$\{([^}]+)\}", compose_text)
    unguarded = [item for item in raw if ":?" not in item]
    assert not unguarded, (
        "Variabel berikut dipakai tanpa guard ':?' sehingga nilai kosong lolos diam-diam: "
        f"{sorted(unguarded)} — pakai ${{VAR:?pesan}}"
    )

    required = {item.split(":?")[0] for item in raw}
    defined = {
        line.split("=", 1)[0].strip()
        for line in example_text.splitlines()
        if line.strip() and not line.strip().startswith("#") and "=" in line
    }
    missing = required - defined
    assert not missing, f"Variables in compose.yml missing from .env.example: {sorted(missing)}"

    # .env.example ikut ter-commit: nilai password di sana wajib masih placeholder.
    for name in ("POSTGRES_PASSWORD", "SOURCE_MYSQL_PASSWORD", "SOURCE_MYSQL_ROOT_PASSWORD"):
        line = next(line for line in example_text.splitlines() if line.startswith(name + "="))
        value = line.split("=", 1)[1].strip()
        assert value.startswith("replace"), (
            f"{name} di deploy/.env.example bukan placeholder lagi ({value!r}) — "
            "secret nyata tidak boleh masuk file yang di-commit"
        )



def test_image_api_memuat_semua_modul_skrip_yang_diload():
    """Setiap load_accreditation_module("x.py") di api/app wajib ikut di-COPY ke image API.

    Regresi nyata: image hanya menyalin registry_kebutuhan_data.py, sehingga generate Word dan
    ekstraksi AI akreditasi pasti gagal di container walau lolos semua uji lokal.
    """
    import re

    dipakai = set()
    for path in (ROOT / "api" / "app").rglob("*.py"):
        dipakai |= set(re.findall(r'load_accreditation_module\("([\w.]+)"\)', path.read_text(encoding="utf-8")))
    dockerfile = (ROOT / "deploy" / "api.Dockerfile").read_text(encoding="utf-8")
    assert dipakai >= {"registry_kebutuhan_data.py", "generate_template.py", "ekstraksi_akreditasi.py"}
    for nama in dipakai:
        assert f"akreditasi/scripts/{nama}" in dockerfile or "COPY akreditasi/scripts " in dockerfile, nama


def test_ekstraksi_ai_opsional_lewat_env_file_yang_tidak_dicommit():
    compose = (ROOT / "deploy" / "compose.yml").read_text(encoding="utf-8")
    assert "path: ./openai.env" in compose and "required: false" in compose
    assert (ROOT / "deploy" / "openai.env.example").is_file()
    assert "/deploy/openai.env" in (ROOT / ".gitignore").read_text(encoding="utf-8").splitlines()


def test_migrasi_menerjemahkan_skema_mysql():
    from deploy.migrate_mysql_to_postgres import Column, TableSchema, create_table_sql, pg_default, pg_type

    assert pg_type("tinyint", "tinyint(1)") == "boolean"
    assert pg_type("int", "int") == "integer"
    assert pg_type("varchar", "varchar(254)") == "varchar(254)"
    assert pg_type("datetime", "datetime") == "timestamp"
    assert pg_type("longtext", "longtext") == "text"
    assert pg_default("0", "", "boolean") == "FALSE"
    assert pg_default("mei", "", "varchar(64)") == "'mei'"
    assert pg_default(None, "auto_increment", "integer") is None
    t = TableSchema("akreditasi_users", [Column("id", "integer", False, None, identity=True),
                                         Column("email", "varchar(254)", False, None),
                                         Column("is_admin", "boolean", False, "FALSE")], ["id"], {"email": ["email"]})
    sql = create_table_sql(t)
    assert '"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL' in sql
    assert '"is_admin" boolean DEFAULT FALSE NOT NULL' in sql and 'PRIMARY KEY ("id")' in sql
