"""Salin database MySQL sumber ke PostgreSQL -- dengan skema yang benar, bukan tebakan pandas.

Dulu skrip ini hanya memakai `pandas.to_sql`, sehingga di PostgreSQL: tidak ada PRIMARY KEY /
UNIQUE, kolom `id` tidak auto-increment (INSERT tanpa id -> NULL), `tinyint(1)` menjadi BIGINT
(API menulis TRUE/FALSE -> galat tipe), dan tabel KOSONG seluruh kolomnya TEXT. Akibatnya
registrasi akun, upload, ekstraksi, dan simpan data akreditasi gagal di server.

Sekarang skema dibaca dari information_schema MySQL lalu diterjemahkan:
  tipe kolom (tinyint(1) -> boolean, int -> integer, datetime -> timestamp, ...), NOT NULL,
  default sederhana, AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY (+ setval ke MAX(id)),
  PRIMARY KEY, dan UNIQUE index.

Dua mode:
  python migrate_mysql_to_postgres.py                  # migrasi awal (menolak kalau target berisi)
  python migrate_mysql_to_postgres.py --perbaiki-skema # server yang SUDAH dimigrasi dgn skrip lama:
                                                       # ubah tipe, tambah PK/UNIQUE/IDENTITY di
                                                       # tempat, data tidak disalin ulang
Env: SOURCE_MYSQL_{HOST,PORT,USER,PASSWORD,DB} dan POSTGRES_{HOST,PORT,USER,PASSWORD,DB}.
"""
from __future__ import annotations

import argparse
import os
import re
from dataclasses import dataclass, field

import pandas as pd
from sqlalchemy import URL, create_engine, inspect, text
from sqlalchemy.engine import Connection, Engine

BATCH_SIZE = 1_000
PERF_INDEXES = [
    ("berita_berita_tanggal_idx", "berita_berita", "tanggal"),
    ("berita_kepmen_url_idx", "berita_berita_kepmen_all", "url"),
    ("berita_sitemap_sdg_url_idx", "berita_sitemap_sdg", "url"),
    ("berita_unit_url_idx", "berita_unit_kerja", "url"),
]


def url(driver: str, prefix: str) -> URL:
    return URL.create(
        driver,
        username=os.environ[f"{prefix}_USER"],
        password=os.environ[f"{prefix}_PASSWORD"],
        host=os.environ[f"{prefix}_HOST"],
        port=int(os.environ[f"{prefix}_PORT"]),
        database=os.environ[f"{prefix}_DB"],
    )


def q(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


@dataclass
class Column:
    name: str
    pg_type: str
    nullable: bool
    default: str | None
    identity: bool = False


@dataclass
class TableSchema:
    name: str
    columns: list[Column] = field(default_factory=list)
    primary_key: list[str] = field(default_factory=list)
    unique: dict[str, list[str]] = field(default_factory=dict)

    @property
    def booleans(self) -> list[str]:
        return [c.name for c in self.columns if c.pg_type == "boolean"]

    @property
    def identity(self) -> Column | None:
        return next((c for c in self.columns if c.identity), None)


def pg_type(data_type: str, column_type: str) -> str:
    """Terjemahkan tipe MySQL (information_schema) ke tipe PostgreSQL."""
    data_type, column_type = data_type.lower(), column_type.lower()
    if column_type.startswith("tinyint(1)"):
        return "boolean"
    if data_type in ("tinyint", "smallint"):
        return "smallint"
    if data_type in ("mediumint", "int", "integer"):
        return "bigint" if "unsigned" in column_type else "integer"
    if data_type == "bigint":
        return "numeric(20)" if "unsigned" in column_type else "bigint"
    if data_type in ("decimal", "numeric"):
        m = re.search(r"\((\d+),(\d+)\)", column_type)
        return f"numeric({m.group(1)},{m.group(2)})" if m else "numeric"
    if data_type in ("float", "double", "real"):
        return "double precision"
    if data_type in ("varchar", "char"):
        m = re.search(r"\((\d+)\)", column_type)
        return f"varchar({m.group(1)})" if m else "text"
    if data_type in ("datetime", "timestamp"):
        return "timestamp"
    if data_type == "date":
        return "date"
    if data_type == "time":
        return "time"
    if data_type in ("blob", "mediumblob", "longblob", "tinyblob", "binary", "varbinary"):
        return "bytea"
    return "text"  # text/longtext/json/enum/set


def pg_default(default: str | None, extra: str, typ: str) -> str | None:
    if default is None or "auto_increment" in extra.lower():
        return None
    if default.upper().startswith("CURRENT_TIMESTAMP"):
        return "CURRENT_TIMESTAMP"
    if typ == "boolean":
        return "TRUE" if default not in ("0", "b'0'") else "FALSE"
    if re.fullmatch(r"-?\d+(\.\d+)?", default) and typ not in ("text",) and not typ.startswith("varchar"):
        return default
    return "'" + default.replace("'", "''") + "'"


def read_mysql_schema(source: Engine) -> dict[str, TableSchema]:
    with source.connect() as conn:
        db = conn.execute(text("SELECT DATABASE()")).scalar()
        schemas: dict[str, TableSchema] = {}
        for r in conn.execute(text("""
            SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA
            FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = :db ORDER BY TABLE_NAME, ORDINAL_POSITION
        """), {"db": db}).mappings():
            typ = pg_type(r["DATA_TYPE"], r["COLUMN_TYPE"])
            schemas.setdefault(r["TABLE_NAME"], TableSchema(r["TABLE_NAME"])).columns.append(Column(
                r["COLUMN_NAME"], typ, r["IS_NULLABLE"] == "YES",
                pg_default(r["COLUMN_DEFAULT"], r["EXTRA"] or "", typ),
                identity="auto_increment" in (r["EXTRA"] or "").lower(),
            ))
        for r in conn.execute(text("""
            SELECT TABLE_NAME, INDEX_NAME, COLUMN_NAME FROM information_schema.STATISTICS
            WHERE TABLE_SCHEMA = :db AND NON_UNIQUE = 0 ORDER BY TABLE_NAME, INDEX_NAME, SEQ_IN_INDEX
        """), {"db": db}).mappings():
            t = schemas.get(r["TABLE_NAME"])
            if t is None:
                continue
            if r["INDEX_NAME"] == "PRIMARY":
                t.primary_key.append(r["COLUMN_NAME"])
            else:
                t.unique.setdefault(r["INDEX_NAME"], []).append(r["COLUMN_NAME"])
    return schemas


def _index_name(table: str, index: str) -> str:
    return f"{table}_{index}_key"[:63]


def create_table_sql(t: TableSchema) -> str:
    cols = []
    for c in t.columns:
        part = f"{q(c.name)} {c.pg_type}"
        if c.identity:
            part += " GENERATED BY DEFAULT AS IDENTITY"
        if c.default is not None:
            part += f" DEFAULT {c.default}"
        if not c.nullable or c.name in t.primary_key:
            part += " NOT NULL"
        cols.append(part)
    if t.primary_key:
        cols.append(f"PRIMARY KEY ({', '.join(q(c) for c in t.primary_key)})")
    return f"CREATE TABLE {q(t.name)} (\n  " + ",\n  ".join(cols) + "\n)"


def constraint_sql(t: TableSchema) -> list[str]:
    return [f"CREATE UNIQUE INDEX IF NOT EXISTS {q(_index_name(t.name, name))} ON {q(t.name)} "
            f"({', '.join(q(c) for c in cols)})" for name, cols in t.unique.items()]


def sync_identity(conn: Connection, t: TableSchema) -> None:
    """Setel sequence IDENTITY ke MAX(id)+1 supaya INSERT berikutnya tidak bentrok dengan data salinan."""
    col = t.identity
    if col is None:
        return
    conn.execute(text(
        f"SELECT setval(pg_get_serial_sequence(:t, :c), COALESCE((SELECT MAX({q(col.name)}) FROM {q(t.name)}), 0) + 1, false)"
    ), {"t": q(t.name), "c": col.name})


def _prepare(frame: pd.DataFrame, t: TableSchema) -> pd.DataFrame:
    for c in t.booleans:
        if c in frame:
            frame[c] = frame[c].map(lambda v: None if pd.isna(v) else bool(int(v))).astype("object")
    return frame


def migrate(source: Engine, target: Engine) -> None:
    schemas = read_mysql_schema(source)
    if not schemas:
        raise SystemExit("Source MySQL has no tables")
    with target.begin() as conn:
        if conn.execute(text("SELECT to_regclass('public.berita_berita')")).scalar():
            raise SystemExit("Target PostgreSQL already contains berita_berita; refusing overwrite "
                             "(server lama? jalankan dengan --perbaiki-skema)")
    for name, t in schemas.items():
        with target.begin() as conn:
            conn.execute(text(create_table_sql(t)))
        total = 0
        for frame in pd.read_sql_table(name, source, chunksize=BATCH_SIZE):
            _prepare(frame, t).to_sql(name, target, if_exists="append", index=False, method="multi", chunksize=BATCH_SIZE)
            total += len(frame)
        with target.begin() as conn:
            for stmt in constraint_sql(t):
                conn.execute(text(stmt))
            sync_identity(conn, t)
        print(f"copied {name}: {total} rows")
    create_perf_indexes(target)
    print("migration complete")


def create_perf_indexes(target: Engine) -> None:
    with target.begin() as conn:
        for idx, table, col in PERF_INDEXES:
            if conn.execute(text("SELECT to_regclass(:t)"), {"t": f"public.{table}"}).scalar():
                conn.execute(text(f"CREATE INDEX IF NOT EXISTS {q(idx)} ON {q(table)} ({q(col)})"))


def _cast(col: str, typ: str) -> str:
    if typ == "boolean":
        # Hasil skrip lama: BIGINT 0/1, atau TEXT '0'/'1' untuk tabel yang dulu kosong.
        return f"CASE WHEN {q(col)} IS NULL THEN NULL ELSE ({q(col)}::text NOT IN ('0', 'false', 'f')) END"
    return f"{q(col)}::{typ}"


def repair(source: Engine, target: Engine) -> None:
    """Perbaiki skema tabel yang dibuat skrip lama (to_sql) tanpa menyalin ulang data."""
    schemas = read_mysql_schema(source)
    insp = inspect(target)
    existing = set(insp.get_table_names())
    for name, t in schemas.items():
        if name not in existing:
            print(f"skip {name}: belum ada di PostgreSQL")
            continue
        current = {c["name"]: str(c["type"]).lower() for c in insp.get_columns(name)}
        pk = insp.get_pk_constraint(name).get("constrained_columns") or []
        with target.begin() as conn:
            col = t.identity
            if col is not None and col.name in current:
                # Baris yang di-INSERT di server lama (tanpa IDENTITY) punya id NULL: beri nomor
                # lanjutan setelah MAX(id) supaya PRIMARY KEY/IDENTITY bisa dipasang.
                filled = conn.execute(text(f"""
                    WITH m AS (SELECT COALESCE(MAX({q(col.name)}), 0) AS mx FROM {q(name)}),
                         n AS (SELECT ctid, ROW_NUMBER() OVER () AS rn FROM {q(name)} WHERE {q(col.name)} IS NULL)
                    UPDATE {q(name)} SET {q(col.name)} = m.mx + n.rn FROM m, n WHERE {q(name)}.ctid = n.ctid
                """)).rowcount
                if filled:
                    print(f"  {name}: {filled} baris ber-{col.name} NULL diberi nomor baru")
            for c in t.columns:
                if c.name not in current:
                    continue
                want = c.pg_type
                have = current[c.name]
                same = (want == have or (want == "integer" and have in ("integer", "bigint"))
                        or (want.startswith("varchar") and have in ("text",) + (want,))
                        or (want == "timestamp" and have.startswith("timestamp")))
                if not same:
                    if c.default is None:
                        conn.execute(text(f"ALTER TABLE {q(name)} ALTER COLUMN {q(c.name)} DROP DEFAULT"))
                    conn.execute(text(f"ALTER TABLE {q(name)} ALTER COLUMN {q(c.name)} TYPE {want} USING {_cast(c.name, want)}"))
                if c.default is not None:
                    conn.execute(text(f"ALTER TABLE {q(name)} ALTER COLUMN {q(c.name)} SET DEFAULT {c.default}"))
                if not c.nullable or c.name in t.primary_key:
                    n_null = conn.execute(text(f"SELECT COUNT(*) FROM {q(name)} WHERE {q(c.name)} IS NULL")).scalar()
                    if n_null:
                        print(f"  PERINGATAN {name}.{c.name}: {n_null} baris NULL -- NOT NULL dilewati, periksa manual")
                    else:
                        conn.execute(text(f"ALTER TABLE {q(name)} ALTER COLUMN {q(c.name)} SET NOT NULL"))
            if t.primary_key and not pk:
                conn.execute(text(f"ALTER TABLE {q(name)} ADD PRIMARY KEY ({', '.join(q(c) for c in t.primary_key)})"))
            if col is not None:
                is_identity = conn.execute(text(
                    "SELECT is_identity FROM information_schema.columns WHERE table_name = :t AND column_name = :c"
                ), {"t": name, "c": col.name}).scalar()
                if is_identity != "YES":
                    conn.execute(text(f"ALTER TABLE {q(name)} ALTER COLUMN {q(col.name)} ADD GENERATED BY DEFAULT AS IDENTITY"))
            for stmt in constraint_sql(t):
                conn.execute(text(stmt))
            sync_identity(conn, t)
        print(f"repaired {name}")
    create_perf_indexes(target)
    print("repair complete")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--perbaiki-skema", action="store_true",
                        help="perbaiki skema PostgreSQL hasil skrip lama, tanpa menyalin ulang data")
    args = parser.parse_args()
    source = create_engine(url("mysql+pymysql", "SOURCE_MYSQL"), pool_pre_ping=True)
    target = create_engine(url("postgresql+psycopg", "POSTGRES"), pool_pre_ping=True)
    (repair if args.perbaiki_skema else migrate)(source, target)


if __name__ == "__main__":
    main()
