"""Kamus kata kunci untuk klasifikasi berita dampak UGM.
"""

KEYWORDS = {
    "rehabilitasi_lingkungan": [
        "rehabilitasi lingkungan",
        "konservasi",
        "restorasi",
        "penghijauan",
        "hutan",
        "kehutanan",
        "forest",
        "forestry",
        "mangrove",
        "deforestasi",
        "ekosistem",
        "habitat",
        "wildlife",
        "biodiversitas",
        "keanekaragaman hayati",
        "tree planting",
        "penanaman pohon",
    ],
    "kewirausahaan": [
        "kewirausahaan",
        "wirausaha",
        "umkm",
        "startup",
        "entrepreneur",
        "entrepreneurship",
        "smes",
        "inkubasi bisnis",
        "spin-off",
        "spin off",
    ],
    "kunjungan_akademik": [
        "kunjungan akademik",
        "studi banding",
        "delegasi",
        "study visit",
        "academic visit",
        "guest lecture",
        "academic delegation",
    ],
    "kolaborasi_riset": [
        "kolaborasi riset",
        "kerja sama penelitian",
        "riset bersama",
        "research collaboration",
        "joint research",
        "research cooperation",
        "kerjasama riset",
        "kerja sama riset",
        "kerjasama penelitian",
        "research partnership",
        "penelitian bersama",
    ],
}
