"""Perbaikan otomatis kolom `id` di PostgreSQL hasil migrasi lama (dijalankan tiap API menyala).

Latar: server pertama kali diisi dengan skrip migrasi lama (pandas `to_sql`) yang membuat kolom `id`
sebagai INTEGER biasa, tanpa IDENTITY/SERIAL. Akibatnya setiap INSERT baru dari aplikasi (daftar
akun, unggah file, dll.) menyimpan `id` NULL. Gejala paling terlihat: akun Akreditasi yang baru
didaftarkan bisa "login", tapi sesinya tercatat untuk user_id NULL sehingga pemeriksaan sesi gagal
dan pengguna kembali ke halaman login; akun lama (id dari salinan MySQL) tetap normal.

`deploy/migrate_mysql_to_postgres.py --perbaiki-skema` memperbaiki ini tapi butuh MySQL sumber dan
dijalankan manual. Modul ini melakukan bagian yang penting tanpa MySQL, idempoten:
1. baris ber-id NULL diberi nomor lanjutan setelah MAX(id);
2. kolom `id` dijadikan NOT NULL + GENERATED BY DEFAULT AS IDENTITY, sequence disetel ke MAX(id)+1;
3. PRIMARY KEY (id) dipasang bila belum ada dan tidak ada id kembar;
4. sesi login yatim (user_id NULL / akun tidak ada) dibuang.
Hanya berlaku di PostgreSQL; dialek lain tidak disentuh.
"""
from __future__ import annotations

import logging

from sqlalchemy import text
from sqlalchemy.engine import Engine

logger = logging.getLogger(__name__)

SESI = {"akreditasi_sessions": "akreditasi_users", "dampak_sessions": "dampak_users"}


def _q(nama: str) -> str:
    return '"' + nama.replace('"', '""') + '"'


def tabel_perlu_diperbaiki(engine: Engine) -> list[str]:
    """Tabel dengan kolom `id` bilangan bulat yang tidak punya IDENTITY maupun DEFAULT (nextval)."""
    with engine.connect() as conn:
        return [r[0] for r in conn.execute(text("""
            SELECT c.table_name
            FROM information_schema.columns c
            JOIN information_schema.tables t ON t.table_schema = c.table_schema AND t.table_name = c.table_name
            WHERE c.table_schema = current_schema() AND t.table_type = 'BASE TABLE'
              AND c.column_name = 'id' AND c.data_type IN ('smallint', 'integer', 'bigint')
              AND c.is_identity = 'NO' AND c.column_default IS NULL
            ORDER BY c.table_name
        """))]


def _perbaiki_tabel(engine: Engine, nama: str) -> str:
    t = _q(nama)
    with engine.begin() as conn:
        diisi = conn.execute(text(f"""
            WITH m AS (SELECT COALESCE(MAX(id), 0) AS mx FROM {t}),
                 n AS (SELECT ctid, ROW_NUMBER() OVER () AS rn FROM {t} WHERE id IS NULL)
            UPDATE {t} SET id = m.mx + n.rn FROM m, n WHERE {t}.ctid = n.ctid
        """)).rowcount
        conn.execute(text(f"ALTER TABLE {t} ALTER COLUMN id SET NOT NULL"))
        conn.execute(text(f"ALTER TABLE {t} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY"))
        conn.execute(text(f"SELECT setval(pg_get_serial_sequence(:t, 'id'), COALESCE((SELECT MAX(id) FROM {t}), 0) + 1, false)"),
                     {"t": t})
        ada_pk = conn.execute(text("""
            SELECT 1 FROM information_schema.table_constraints
            WHERE table_schema = current_schema() AND table_name = :n AND constraint_type = 'PRIMARY KEY'
        """), {"n": nama}).first()
        kembar = conn.execute(text(f"SELECT 1 FROM {t} GROUP BY id HAVING COUNT(*) > 1 LIMIT 1")).first()
        if not ada_pk and not kembar:
            conn.execute(text(f"ALTER TABLE {t} ADD PRIMARY KEY (id)"))
    catatan = f"{nama}: id otomatis dipasang" + (f", {diisi} baris ber-id kosong diberi nomor" if diisi else "")
    return catatan + (" (id kembar, PRIMARY KEY dilewati)" if kembar else "")


def _buang_sesi_yatim(engine: Engine) -> None:
    with engine.begin() as conn:
        for sesi, users in SESI.items():
            if not conn.execute(text("SELECT to_regclass(:t)"), {"t": sesi}).scalar():
                continue
            n = conn.execute(text(f"""
                DELETE FROM {_q(sesi)} s
                WHERE s.user_id IS NULL OR NOT EXISTS (SELECT 1 FROM {_q(users)} u WHERE u.id = s.user_id)
            """)).rowcount
            if n:
                logger.warning("%s: %d sesi yatim dibuang", sesi, n)


def perbaiki(engine: Engine) -> list[str]:
    """Jalankan semua perbaikan; tiap tabel dalam transaksinya sendiri supaya satu kegagalan tidak menahan yang lain."""
    if engine.dialect.name != "postgresql":
        return []
    hasil: list[str] = []
    for nama in tabel_perlu_diperbaiki(engine):
        try:
            hasil.append(_perbaiki_tabel(engine, nama))
            logger.warning("perbaikan skema: %s", hasil[-1])
        except Exception:  # noqa: BLE001 -- lanjutkan tabel lain; detail di log
            logger.exception("perbaikan skema gagal untuk tabel %s", nama)
    try:
        _buang_sesi_yatim(engine)
    except Exception:  # noqa: BLE001
        logger.exception("pembersihan sesi yatim gagal")
    return hasil
